### ISSUE TITLE
Error encountered with "Generate configs" task when default "client_wireguard_path" value is used

### ISSUE THREAD

**Issue by dsofeir** [mawalu/wireguard-private-networking#15]
# Issue
I have encountered the following error when applying the role using the default value for variable `client_wireguard_path`:

```
TASK [mawalu.wireguard-private-networking : Generate configs] *************************
fatal: [host.example.com]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'content'"}
```
# Cause
The default value for `client_wireguard_path` is "~/wg.conf" which is set in defaults/main.yml. I believe the error occurs because the test in the template interface.conf.j2 (`client_wireguard_path | length > 0`) never evaluates to false because the variable `client_wireguard_path` will never have a zero length.

# Solution 
Setting variable `client_wireguard_path = ""` in defaults/main.yml resolves the issue

**Comment by mawalu** [comment]
Thanks for report this, this check should indeed use `client_vpn_ip` instead of the path. Could you check if the current master with the updated check works for you without setting the path?

**Comment by dsofeir** [comment]
Yes, that works. Thank you 👍
