### ISSUE TITLE
Add support for the Ansible --check option

### ISSUE THREAD

**Issue by promethe42** [mawalu/wireguard-private-networking#30]
Hi,

I looks like the `Read private key` task fails in check mode (`ansible-playbook --check`). Presumably because the private key is not actually created in the first place in check mode:

```
TASK [mawalu.wireguard_private_networking : Read private key] ******************
ok: [vpn-server]
fatal: [minecraft]: FAILED! => {"changed": false, "msg": "file not found: /etc/wireguard/privatekey"}
```

The task is ok for the `vpn-server` host because it was already provisioned and the `/etc/wireguard/privatekey` file does exist. Which is not the case for the `minecraft` host: it's a new machine.

I'll open a PR to fix this.

**Comment by mawalu** [comment]
Resolved by #31
